# Generated by Django 5.1.6 on 2025-03-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0002_achievement_cause_teammember_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(help_text='Recommended size: e.g., 1920x800 pixels', upload_to='banner_images/')),
                ('button_text', models.CharField(blank=True, default='Donate Now', max_length=50)),
                ('button_link', models.CharField(blank=True, default='#donate-section-anchor', help_text='URL or #anchor for the button', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance (lower numbers first).')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide on the website.')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
