# Generated by Django 5.1.6 on 2025-04-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0003_bannerslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslide',
            name='button_action',
            field=models.CharField(choices=[('link', 'Link'), ('donate', 'Open Donate Popup'), ('volunteer', 'Open Volunteer Popup')], default='link', help_text='What should the button do?', max_length=20),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='button_link',
            field=models.CharField(blank=True, default='#', help_text="URL (#anchor, page URL) or leave '#' for popup actions", max_length=255),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='button_text',
            field=models.CharField(blank=True, default='Learn More', max_length=50),
        ),
    ]
