# Generated by Django 5.1.6 on 2025-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0004_bannerslide_button_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='image',
            field=models.ImageField(help_text='Recommended size: e.g., 1920x800 pixels', upload_to='images/banner_images/'),
        ),
    ]
