# Generated by Django 4.2 on 2026-03-18 13:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0008_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesection",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
